spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessactivity
      database: fitnessactivity

server:
  port:  8082

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    activity.queue
  routing:
    activity.tracking