spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql ://localhost:5432/fitness_user_db
    username: postgres
    password: A.sdfghjkl12345
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

